#############################################################################
# Makefile for building: bin/Toravist
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri May 16 15:26:46 2014
# Project:  Toravist.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Toravist.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iinclude -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/Toravist.cpp \
		src/AttributeAxis.cpp \
		src/AxesLayout.cpp \
		src/AxesPairLink.cpp \
		src/DataComponent.cpp \
		src/DataEntry.cpp \
		src/PointOnAxis.cpp \
		src/PointsOnAxisLink.cpp \
		src/Pattern.cpp \
		src/Task.cpp moc_AxesLayout.cpp \
		moc_Toravist.cpp
OBJECTS       = obj/main.o \
		obj/Toravist.o \
		obj/AttributeAxis.o \
		obj/AxesLayout.o \
		obj/AxesPairLink.o \
		obj/DataComponent.o \
		obj/DataEntry.o \
		obj/PointOnAxis.o \
		obj/PointsOnAxisLink.o \
		obj/Pattern.o \
		obj/Task.o \
		obj/moc_AxesLayout.o \
		obj/moc_Toravist.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Toravist.pro
QMAKE_TARGET  = Toravist
DESTDIR       = bin/
TARGET        = bin/Toravist

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Toravist.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Toravist.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Toravist.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Toravist1.0.0 || $(MKDIR) obj/Toravist1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Toravist1.0.0/ && $(COPY_FILE) --parents include/AttributeAxis.hpp include/AxesLayout.hpp include/AxesPairLink.hpp include/PointOnAxis.hpp include/PointsOnAxisLink.hpp include/DataComponent.hpp include/DataEntry.hpp include/Pattern.hpp include/Task.hpp include/Toravist.hpp obj/Toravist1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Toravist.cpp src/AttributeAxis.cpp src/AxesLayout.cpp src/AxesPairLink.cpp src/DataComponent.cpp src/DataEntry.cpp src/PointOnAxis.cpp src/PointsOnAxisLink.cpp src/Pattern.cpp src/Task.cpp obj/Toravist1.0.0/ && (cd `dirname obj/Toravist1.0.0` && $(TAR) Toravist1.0.0.tar Toravist1.0.0 && $(COMPRESS) Toravist1.0.0.tar) && $(MOVE) `dirname obj/Toravist1.0.0`/Toravist1.0.0.tar.gz . && $(DEL_FILE) -r obj/Toravist1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_AxesLayout.cpp moc_Toravist.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AxesLayout.cpp moc_Toravist.cpp
moc_AxesLayout.cpp: include/AxesLayout.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/AxesLayout.hpp -o moc_AxesLayout.cpp

moc_Toravist.cpp: include/Toravist.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/Toravist.hpp -o moc_Toravist.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp include/Toravist.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/Toravist.o: src/Toravist.cpp include/Toravist.hpp \
		include/DataComponent.hpp \
		include/DataEntry.hpp \
		include/AxesLayout.hpp \
		include/AttributeAxis.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Toravist.o src/Toravist.cpp

obj/AttributeAxis.o: src/AttributeAxis.cpp include/AttributeAxis.hpp \
		include/AxesLayout.hpp \
		include/DataComponent.hpp \
		include/PointOnAxis.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/AttributeAxis.o src/AttributeAxis.cpp

obj/AxesLayout.o: src/AxesLayout.cpp include/AttributeAxis.hpp \
		include/AxesPairLink.hpp \
		include/AxesLayout.hpp \
		include/DataComponent.hpp \
		include/PointOnAxis.hpp \
		include/PointsOnAxisLink.hpp \
		include/Task.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/AxesLayout.o src/AxesLayout.cpp

obj/AxesPairLink.o: src/AxesPairLink.cpp include/AxesPairLink.hpp \
		include/AttributeAxis.hpp \
		include/DataComponent.hpp \
		include/PointOnAxis.hpp \
		include/PointsOnAxisLink.hpp \
		include/DataEntry.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/AxesPairLink.o src/AxesPairLink.cpp

obj/DataComponent.o: src/DataComponent.cpp include/AttributeAxis.hpp \
		include/DataEntry.hpp \
		include/DataComponent.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/DataComponent.o src/DataComponent.cpp

obj/DataEntry.o: src/DataEntry.cpp include/AttributeAxis.hpp \
		include/DataComponent.hpp \
		include/DataEntry.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/DataEntry.o src/DataEntry.cpp

obj/PointOnAxis.o: src/PointOnAxis.cpp include/AttributeAxis.hpp \
		include/DataComponent.hpp \
		include/DataEntry.hpp \
		include/PointOnAxis.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PointOnAxis.o src/PointOnAxis.cpp

obj/PointsOnAxisLink.o: src/PointsOnAxisLink.cpp include/PointOnAxis.hpp \
		include/PointsOnAxisLink.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PointsOnAxisLink.o src/PointsOnAxisLink.cpp

obj/Pattern.o: src/Pattern.cpp include/Pattern.hpp \
		include/AttributeAxis.hpp \
		include/DataComponent.hpp \
		include/PointOnAxis.hpp \
		include/DataEntry.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Pattern.o src/Pattern.cpp

obj/Task.o: src/Task.cpp include/Task.hpp \
		include/AttributeAxis.hpp \
		include/DataComponent.hpp \
		include/PointOnAxis.hpp \
		include/DataEntry.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Task.o src/Task.cpp

obj/moc_AxesLayout.o: moc_AxesLayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_AxesLayout.o moc_AxesLayout.cpp

obj/moc_Toravist.o: moc_Toravist.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_Toravist.o moc_Toravist.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

