######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 15 22:54:44 2014
######################################################################

TEMPLATE = app
TARGET = Toravist
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AttributeAxis.hpp \
           DataComponent.hpp \
           DataEntry.hpp \
           TargetConstraintPair.hpp \
           Task.hpp
SOURCES += main.cpp
